spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost/tesla_project
    username: tesla_project
    password: tesla_user
com:
  tesla:
    baseUrl: https://owner-api.teslamotors.com/
    tokenUrl: /oauth/token/
    vehiclesUrl: /api/1/vehicles/
    clientId: 81527cff06843c8634fdc09e8ac0abefb46ac849f38fe1e431c2ef2106796384
    clientSecret: c7257eb71a564034f9419ee651c7d0e5f7aa6bfbd18bafb5c5c033b093bb2fa3
    wssUrl: wss://streaming.vn.teslamotors.com/streaming/
redis:
  host: localhost
  port: 6379
